export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const GET_POSTS = 'GET_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';

export const ADD_PURCHASE_ORDER = 'ADD_PURCHASE_ORDER';
export const GET_PURCHASE_ORDERS = 'GET_PURCHASE_ORDERS';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REQUEST_CHECK_TOKEN = 'REQUEST_CHECK_TOKEN';
export const TOKEN_VALID = 'TOKEN_VALID';
export const TOKEN_INVALID = 'TOKEN_INVALID';

export const CHARGE_REQUEST = 'CHARGE_REQUEST';
export const CHARGE_SUCCESS = 'CHARGE_SUCCESS';
export const CHARGE_FAILURE = 'CHARGE_FAILURE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_SELECTED_PRODUCT = 'ADD_SELECTED_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

export const TOGGLE_CONTACT_FORM = 'TOGGLE_CONTACT_FORM';
export const SEND_CONTACT_FORM = 'SEND_CONTACT_FORM';
export const ADD_MESSAGES = 'ADD_MESSAGES';
